### PR TITLE
Associate sponcers (Pipal)

### PR DESCRIPTION
**Pull request by pushplataranjan**

### CODE REVIEW

**Comment by anandology** [comment]
@pushp Thanks for making the PR. Could you please change the heading to "Pipal Academy" From "PIPAL"? 

Could you also change "Visit PIPAL website" to "Visit Pipal Academy website".

May I know why `?ref=pyconindia2016` is added to the link? I don't think that has any affect. It'll be better if that is omitted.

**Comment by pushplataranjan** [comment]
@anandology . Thanks for the feedback. Changed PIPAL to Pipal Academy.

**Comment by pushplataranjan** [comment]
@anandology ?ref=pyconindia2016 is used for referral tracking .

**Comment by akshayaurora** [comment]
@pushp thanks

**Pull request merged**
