### PR TITLE
Added IRC and hash tag on main page + makes CSS file consistent

### PR DESCRIPTION
**Pull request by CuriousLearner**
This PR adds IRC and hash tag on the index page of the site.

The current CSS files had tabs and spaces mixed + different indentation levels.

I've made it consistent with 4 spaces indentation + removed extra spaces.

### CODE REVIEW

**Comment by theskumar** [comment]
1. Add editorconfig? 
2. providing a screenshot would help!

Nice work!

**Comment by CuriousLearner** [comment]
Sure, I'll add `.editorconfig` 

Though what should be the configuration for it? Is Fossevents one good enough?

Here is the screenshot:
screen shot 2016-03-28 at 20 50 38

**Comment by theskumar** [comment]
Let's use the one from https://github.com/h5bp/html5-boilerplate/blob/master/.editorconfig

**Comment by CuriousLearner** [comment]
@theskumar Please have a look now.

**Comment by theskumar** [comment]
The irc channel is #pyconindia 
- Remove these from above the main buttons, instead replace the `Desinged by` copy with three hyperlinks in the footer.

[IRC](https://webchat.freenode.net/?channels=%23pyconindia) | [Mailing List](https://mail.python.org/mailman/listinfo/inpycon) | [#pyconindia](https://twitter.com/search?q=pyconindia)

**Pull request closed without merging**
