### PR TITLE
Adding carousel for previous year speakers

### PR DESCRIPTION
**Pull request by CuriousLearner**
Carousel added.

cc @theskumar @satyaakam 

Please let me know if changes are needed.

### CODE REVIEW

**Comment by CuriousLearner** [comment]
Adding screen-shots:

screen shot 2016-07-04 at 23 59 35
screen shot 2016-07-04 at 23 59 26

**Comment by CuriousLearner** [comment]
Hi @satyaakam 

Any updates on this? Do we still need this?

**Comment by satyaakam** [comment]
@CuriousLearner Yeah its irrelevant as of now we can close this request as of now .

**Comment by CuriousLearner** [comment]
Thanks! 

Closing it now.

**Pull request closed without merging**
