### PR TITLE
Adding writeup for sponsors using bootstrap modals

### PR DESCRIPTION
**Pull request by CuriousLearner**
Here are the screenshots for the same:

screen shot 2016-08-29 at 12 40 36 am
screen shot 2016-08-29 at 12 55 15 am

For sponsors that have details on site but no description:

screen shot 2016-08-29 at 12 54 08 am

All other placeholders for sponsor won't show the modal at all.

Let me know if there are any other changes needed :)

cc @akshayaurora @satyaakam

### CODE REVIEW

**Comment by theskumar** [comment]
This is look good, just some minor updates you can do:
1. Don't center align body text
2. Put the logo in the pop-up as well, can either go in the `title` or first thing in the body text.
3. Put 1em left & right padding for body text.

Let me know when done, (also you'll need to resolve merge conflict with master)

Cheers

**Comment by CuriousLearner** [comment]
Hi @theskumar 

I've done the above changes :)

Have used 2em padding instead of 1 since it was still cluttering in case of lists!

**Comment by CuriousLearner** [comment]
@theskumar Also added writeup for RedHat and JetBrains

cc @akshayaurora  @satyaakam

**Comment by satyaakam** [comment]
Anyone looking into this PR it has conflics

**Comment by akshayaurora** [comment]
@CuriousLearner could you please rebase

**Comment by CuriousLearner** [comment]
Argh... so many changes in-between :(

Resolving and updating in few minutes. Please do not merge

**Comment by CuriousLearner** [comment]
Please check now!
I've tried to accommodate all changes but it might be possible that some other changes are overrided.

@satyaakam @akshayaurora

**Comment by akshayaurora** [comment]
@theskumar @kracekumar could you folks look this over and merge please.

**Comment by theskumar** [comment]
Thanks @CuriousLearner for the hard work. this is deployed now.

**Comment by CuriousLearner** [comment]
Thanks @theskumar :)

**Pull request closed without merging**
