### PR TITLE
Talks arranged as per rooms and timings

### PR DESCRIPTION
**Pull request by harshuljain13**

### CODE REVIEW

**Comment by vnbang2003** [comment]
@harshul1610 Does this schedule changes have all 3 rooms schedule ?

**Comment by CuriousLearner** [comment]
@harshul1610 Please remove the files under .idea/

They are not needed.

**Comment by bhanuvrat** [comment]
included in https://github.com/pythonindia/inpycon2016/pull/98

**Comment by CuriousLearner** [comment]
Thanks!

**Pull request closed without merging**
